logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 110.41.157.223 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: xinzhu # 用户名
    password: xinzhu # 密码