logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 110.41.157.223 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: xinzhu # 用户名
    password: xinzhu # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
        acknowledge-mode: auto # none 关闭ack
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000 # 初始等待时长为1秒
          multiplier: 2 # 失败的等待时长倍数
          max-attempts: 3 # 最大重试次数