spring:
  application:
    name: springdataredis_demo
  #Redis相关配置
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 1 #操作的是0号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    sentinel:
      master: mymaster
      nodes:
        - 192.168.100.150:27001
        - 192.168.100.150:27002
        - 192.168.100.150:27003
    cluster:
      nodes:
        - 192.168.100.150:7001
        - 192.168.100.150:7002
        - 192.168.100.150:7003
        - 192.168.100.150:7004
        - 192.168.100.150:7005
        - 192.168.100.150:7006