server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 110.41.157.223
    port: 5672
    username: xinzhu
    password: xinzhu
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: space.xinzhu.es