docker network create es-net

docker run -d \
--name es --restart=always \
-e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
-e "discovery.type=single-node" \
-v es-data:/usr/share/elasticsearch/data \
-v es-plugins:/usr/share/elasticsearch/plugins \
--privileged \
--network es-net \
-p 9200:9200 \
-p 9300:9300 \
elasticsearch:7.12.1

# - `-e "cluster.name=es-docker-cluster"`：设置集群名称
# - `-e "http.host=0.0.0.0"`：监听的地址，可以外网访问
# - `-e "ES_JAVA_OPTS=-Xms512m -Xmx512m"`：内存大小
# - `-e "discovery.type=single-node"`：非集群模式
# - `-v es-data:/usr/share/elasticsearch/data`：挂载逻辑卷，绑定es的数据目录
# - `-v es-logs:/usr/share/elasticsearch/logs`：挂载逻辑卷，绑定es的日志目录
# - `-v es-plugins:/usr/share/elasticsearch/plugins`：挂载逻辑卷，绑定es的插件目录
# - `--privileged`：授予逻辑卷访问权
# - `--network es-net` ：加入一个名为es-net的网络中
# - `--restart=always`：开机自启
# - `-p 9200:9200`：端口映射配置

docker run -d \
--name kibana  --restart=always \
-e ELASTICSEARCH_HOSTS=http://es:9200 \
--network=es-net \
-p 5601:5601  \
kibana:7.12.1